AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Function checking CMK auto rotation and enabling.
Resources:
  lambda_function:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.10
      Role: ## Need to write this
      Handler: auto_rotate.handler # double check this too
      Code:
        ZipFile:  |
          def lambda_handler(event, context):
              client = boto3.client('kms')
              # get a list of all kms keys
              response = client.list_keys()
              cmk_list = response['Keys']

              # iterate over the key list to get the Key Ids
              for cmk in cmk_list:
                  key_id = cmk['KeyId']

                  # finally enable the rotation
                  try: 
                      client.enable_key_rotation(KeyId=key_id)
                      print(f"Automatic rotation enabled for Key: {key_id}.")
                  except Exception as e:
                      print(f"Error enabling key rotation for CMK: {key_id}. Error: {str(e)}")
  
