AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Function checking CMK auto rotation and enabling.
Resources:
  lambda_function:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.10
      Role: ## Need to write this
      Handler: auto_rotate.handler # double check this too
      Code:
        ZipFile:  |
          def lambda_handler(event, context):
              client = boto3.client('kms')
              # get a list of all kms keys
              response = client.list_keys()
              cmk_list = response['Keys']

              # iterate over the key list to get the Key Ids
              for cmk in cmk_list:
                  key_id = cmk['KeyId']

                  # finally enable the rotation
                  try: 
                      client.enable_key_rotation(KeyId=key_id)
                      print(f"Automatic rotation enabled for Key: {key_id}.")
                  except Exception as e:
                      print(f"Error enabling key rotation for CMK: {key_id}. Error: {str(e)}")
  execution_role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cmk_auto_rotation_role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam:aws:policy/AWSLambdaExecute
      # kms:EnableKeyRotation is a kms key policy not an IAM policy so need to figure that out first
